#docker-compose.yml
version: '3'
services:
  apollo:
    build:
        context: ./docker_files
        dockerfile: ./apollo_files/Dockerfile
    volumes:
      - ./gzilla:/gzilla
    tty: true
    stdin_open: true
    networks:
      local_net:
        ipv4_address: 172.22.0.4
  attacker:
    build:
        context: ./docker_files
        dockerfile: ./attacker_files/Dockerfile
    volumes:
      - ./gzilla:/gzilla
    tty: true
    stdin_open: true
    networks:
      local_net:
        ipv4_address: 172.22.0.5
networks:
  local_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16

