# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './uifiles/gzilla.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1288, 789)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit = Qsci.QsciScintilla(self.frame)
        self.textEdit.setToolTip("")
        self.textEdit.setWhatsThis("")
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.treeView = QtWidgets.QTreeView(self.frame_2)
        self.treeView.setObjectName("treeView")
        self.gridLayout_3.addWidget(self.treeView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tree_sync_button = QtWidgets.QPushButton(self.frame_3)
        self.tree_sync_button.setObjectName("tree_sync_button")
        self.gridLayout_4.addWidget(self.tree_sync_button, 2, 0, 1, 1)
        self.new_sniff_button = QtWidgets.QPushButton(self.frame_3)
        self.new_sniff_button.setObjectName("new_sniff_button")
        self.gridLayout_4.addWidget(self.new_sniff_button, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_4.addItem(spacerItem1, 2, 1, 1, 1)
        self.new_icmp_button = QtWidgets.QPushButton(self.frame_3)
        self.new_icmp_button.setObjectName("new_icmp_button")
        self.gridLayout_4.addWidget(self.new_icmp_button, 1, 6, 1, 1)
        self.run_button = QtWidgets.QPushButton(self.frame_3)
        self.run_button.setObjectName("run_button")
        self.gridLayout_4.addWidget(self.run_button, 1, 0, 1, 1)
        self.new_dns_button = QtWidgets.QPushButton(self.frame_3)
        self.new_dns_button.setObjectName("new_dns_button")
        self.gridLayout_4.addWidget(self.new_dns_button, 2, 6, 1, 1)
        self.new_spoof_button = QtWidgets.QPushButton(self.frame_3)
        self.new_spoof_button.setObjectName("new_spoof_button")
        self.gridLayout_4.addWidget(self.new_spoof_button, 1, 2, 1, 1)
        self.new_ethernet_button = QtWidgets.QPushButton(self.frame_3)
        self.new_ethernet_button.setObjectName("new_ethernet_button")
        self.gridLayout_4.addWidget(self.new_ethernet_button, 1, 4, 1, 1)
        self.new_ip_button = QtWidgets.QPushButton(self.frame_3)
        self.new_ip_button.setObjectName("new_ip_button")
        self.gridLayout_4.addWidget(self.new_ip_button, 2, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_4.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_4.addItem(spacerItem3, 2, 3, 1, 1)
        self.new_tcp_button = QtWidgets.QPushButton(self.frame_3)
        self.new_tcp_button.setObjectName("new_tcp_button")
        self.gridLayout_4.addWidget(self.new_tcp_button, 2, 5, 1, 1)
        self.new_udp_button = QtWidgets.QPushButton(self.frame_3)
        self.new_udp_button.setObjectName("new_udp_button")
        self.gridLayout_4.addWidget(self.new_udp_button, 1, 5, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tree_sync_button.setText(_translate("MainWindow", "Sync From Tree"))
        self.new_sniff_button.setText(_translate("MainWindow", "sniffer"))
        self.new_icmp_button.setText(_translate("MainWindow", "ICMP"))
        self.run_button.setText(_translate("MainWindow", "Save and Run"))
        self.new_dns_button.setText(_translate("MainWindow", "DNS"))
        self.new_spoof_button.setText(_translate("MainWindow", "sender"))
        self.new_ethernet_button.setText(_translate("MainWindow", "Ethernet"))
        self.new_ip_button.setText(_translate("MainWindow", "IP"))
        self.new_tcp_button.setText(_translate("MainWindow", "TCP"))
        self.new_udp_button.setText(_translate("MainWindow", "UDP"))


from PyQt5 import Qsci
